include_guard(GLOBAL)

set(WSP_LOG_CONSOLE_LEVEL "INFO" CACHE STRING
  "Minimum WSP console logging level")
set(WSP_LOG_FILE_LEVEL "DEBUG" CACHE STRING
  "Minimum WSP file logging level")
set(WSP_LOG_COLOR "AUTO" CACHE STRING
  "WSP logging color mode: AUTO, ALWAYS, or NEVER")
set(WSP_LOG_FILE "" CACHE FILEPATH
  "Optional plain-text WSP configure log")

set_property(CACHE WSP_LOG_CONSOLE_LEVEL PROPERTY STRINGS
  DEBUG INFO PASS WARN ERROR OFF)
set_property(CACHE WSP_LOG_FILE_LEVEL PROPERTY STRINGS
  DEBUG INFO PASS WARN ERROR OFF)
set_property(CACHE WSP_LOG_COLOR PROPERTY STRINGS AUTO ALWAYS NEVER)

function(_wsp_log_level_value level result)
  string(TOUPPER "${level}" normalized)
  set(levels DEBUG INFO PASS WARN ERROR OFF)
  list(FIND levels "${normalized}" value)
  if(value EQUAL -1)
    message(FATAL_ERROR "Invalid WSP log level: ${level}")
  endif()
  set("${result}" "${value}" PARENT_SCOPE)
endfunction()

function(_wsp_log_color_enabled result)
  string(TOUPPER "${WSP_LOG_COLOR}" mode)
  if(DEFINED ENV{NO_COLOR} AND NOT "$ENV{NO_COLOR}" STREQUAL "")
    set(enabled FALSE)
  elseif(mode STREQUAL "ALWAYS")
    set(enabled TRUE)
  elseif(mode STREQUAL "NEVER")
    set(enabled FALSE)
  elseif(mode STREQUAL "AUTO")
    if(DEFINED ENV{WT_SESSION} OR DEFINED ENV{TERM})
      set(enabled TRUE)
    else()
      set(enabled FALSE)
    endif()
  else()
    message(FATAL_ERROR "Invalid WSP log color mode: ${WSP_LOG_COLOR}")
  endif()
  set("${result}" "${enabled}" PARENT_SCOPE)
endfunction()

function(wsp_log level text)
  string(TOUPPER "${level}" normalized)
  _wsp_log_level_value("${normalized}" message_value)
  _wsp_log_level_value("${WSP_LOG_CONSOLE_LEVEL}" console_value)
  _wsp_log_level_value("${WSP_LOG_FILE_LEVEL}" file_value)

  if(normalized STREQUAL "INFO")
    set(tag "INFO ")
  elseif(normalized STREQUAL "PASS")
    set(tag "PASS ")
  elseif(normalized STREQUAL "WARN")
    set(tag "WARN ")
  else()
    set(tag "${normalized}")
  endif()

  if(message_value GREATER_EQUAL console_value)
    _wsp_log_color_enabled(use_color)
    if(use_color)
      string(ASCII 27 escape)
      if(normalized STREQUAL "DEBUG")
        set(color "${escape}[33m")
      elseif(normalized STREQUAL "INFO")
        set(color "${escape}[34m")
      elseif(normalized STREQUAL "PASS")
        set(color "${escape}[32m")
      elseif(normalized STREQUAL "WARN")
        set(color "${escape}[93m")
      else()
        set(color "${escape}[31m")
      endif()
      message("${color}[${tag}]${escape}[0m ${text}")
    else()
      message("[${tag}] ${text}")
    endif()
  endif()

  if(NOT WSP_LOG_FILE STREQUAL "" AND
      message_value GREATER_EQUAL file_value)
    get_filename_component(log_parent "${WSP_LOG_FILE}" DIRECTORY)
    if(NOT log_parent STREQUAL "")
      file(MAKE_DIRECTORY "${log_parent}")
    endif()
    string(TIMESTAMP timestamp "%Y-%m-%dT%H:%M:%SZ" UTC)
    file(APPEND "${WSP_LOG_FILE}"
      "${timestamp} [${tag}] ${text}\n")
  endif()
endfunction()

function(wsp_log_fatal text)
  wsp_log(ERROR "${text}")
  message(FATAL_ERROR "${text}")
endfunction()
